create table gaming_platform (
	gaming_platform_id integer not null primary key generated by default as identity,
    name text not null unique
);

insert
into gaming_platform (
    name
)
values
(
    'Sony Playstation'
),
(
    'Nintendo Switch'
),
(
    'Microsoft Xbox'
),
(
    'Computer'
),
(
    'None'
);

create table article_type (
    article_type_id integer not null primary key generated by default as identity,
    name text not null unique
);

insert
into article_type (
    name
)
values
(
    'review'
),
(
    'news'
),
(
    'other'
);

create table article (
    article_id bigint not null primary key generated by default as identity,
    title text not null,
    played_on_gaming_platform_id integer null references gaming_platform (gaming_platform_id),
    producer text null,
    play_time integer null,
    created_at timestamptz not null default now(),
    article_type_id integer not null references article_type (article_type_id),
    short_description text not null,
    long_description text not null
);

create table article_gaming_platform (
    article_id bigint not null
        references article (article_id)
            on delete cascade,
    gaming_platform_id integer not null 
        references gaming_platform (gaming_platform_id),
    PRIMARY KEY (article_id, gaming_platform_id)
);

create index gaming_platform_id_idx on gaming_platform (gaming_platform_id);
create index article_gaming_platform_gaming_platform_id_idx on article_gaming_platform (gaming_platform_id);