create table gaming_platform (
	gaming_platform_id integer not null primary key generated by default as identity,
    gaming_platform_name text not null unique
);

insert
into gaming_platform (
    gaming_platform_name
)
values
(
    'Sony Playstation'
),
(
    'Nintendo Switch'
),
(
    'Microsoft Xbox'
),
(
    'Computer'
),
(
    'None'
);

create table genre (
    genre_id integer not null primary key generated by default as identity,
    genre_name text not null unique
);

insert
into genre (
    genre_name
)
values
(
    'review'
),
(
    'news'
),
(
    'other'
);

create table article (
    article_id bigint not null primary key generated by default as identity,
    title text not null,
    played_on integer null references gaming_platform (gaming_platform_id),
    producer text null,
    play_time integer null,
    created_at timestamptz not null default now(),
    genre_id integer not null references genre (genre_id),
    short_description text not null,
    long_description text not null
);

create table article_gaming_platform (
    article_id bigint not null
        references article (article_id)
            on delete cascade,
    gaming_platform_id integer not null 
        references gaming_platform (gaming_platform_id),
    PRIMARY KEY (article_id, gaming_platform_id)
);