create table article_gallery (
    image_id integer not null primary key generated by default as identity,
    image_filename text not null,
    article_id bigint not null
        references article (article_id)
            on delete cascade
);