create table article_image (
    article_image_id integer not null primary key generated by default as identity,
    file_name text not null,
    is_active boolean not null,
    article_id bigint not null
        references article (article_id)
            on delete cascade
);