create table author (
    author_id integer not null primary key generated by default as identity,
    author_firebase_id text not null unique,
    author_name text not null unique,
    author_description_pl text not null,
    author_description_en text not null
);

insert
into author (
    author_firebase_id,
    author_name,
    author_description_pl,
    author_description_en
)
values
(
    'tyNb24iSjGPBGJUZeLQut4QV0Pu2',
    'Michał Kubrak',
    'Urodzony 4 stycznia 1990 roku w Łomży (miasto w północno-wschodniej Polsce). Z wykształcenia inżynier informatyk. 
    Początkujący programista. Fan gier video, gier planszowych, horrorów i ciężkiej muzyki.',
    'Born on January 4, 1990 in Lomza (city in north-eastern Poland). An IT engineer.
    Beginner programmer. Fan of video games, board games, horrors and heavy music.'
);

alter table article
    add column created_by integer not null references author (author_id)
    default 1;