create table author (
    author_id integer not null primary key generated by default as identity,
    firebase_id text not null unique,
    name text not null unique,
    description_pl text not null,
    description_en text not null
);

insert
into author (
    firebase_id,
    name,
    description_pl,
    description_en
)
values
(
    'unique1',
    'John Doe',
    'Polish Lorem ipsum',
    'English Lorem ipsum'
);

alter table article
    add column created_by_author_id integer not null references author (author_id)
    default 1;