alter table article
    drop column if exists created_by_author_id cascade;

drop table if exists author;

create table author (
    author_id integer not null primary key generated by default as identity,
    firebase_id text not null unique,
    name text not null unique,
    description_pl text not null,
    description_en text not null
);